### PR TITLE
bonus level added

### PR DESCRIPTION
**Pull request by Krasios**
It feels like chasing butterflies; any necessary adjustments only need to be made on swarmCtrl

### CODE REVIEW

**Comment by Krasios** [comment]
The force push was me rebasing develop onto master for a cleaner git log
Just needs some edits in mothershipCtrl to switch scenes after getting 3000 light

**Comment by connsteele** [comment]
I couldn't really find the enemies at all in the bonus level. I tried 3x times and only found them 1x time

**Comment by Krasios** [comment]
Alrighty, should I up the number of enemies and pull back the camera a bit?

**Comment by connsteele** [comment]
That sounds like it could work

**Comment by Krasios** [comment]
Went with adding a new method on the swarm, just in case we want to use this enemy type in other levels as an easy light source or something

**Comment by connsteele** [comment]
I'll pull and check it out

**Comment by connsteele** [comment]
Looks great, the enemy ships kind of look like turtles

**Pull request merged**
