### PR TITLE
added restrictions on camera and players since players being too far …

### PR DESCRIPTION
**Pull request by Krasios**
…will affect visuals

### CODE REVIEW

**Comment by Krasios** [comment]
Could someone with a controller pls test this out?
Some of the people from the class playtest complained about when they got too tiny after running away from the obstacles

**Comment by connsteele** [comment]
I'll test it right now. I'll also integrate my lab 4

**Comment by connsteele** [comment]
Uploading a video rn demoing it.

**Comment by connsteele** [comment]
I don't think it works the player still gets really small when far away.
this part it lateUpdate of CameraCtrl looks weird to me
"
distance = Vector2.Distance(player1.transform.position,player2.transform.position);
        offset.z = (distance > 50)? ((distance < 100)? -25 - (distance/2):-75):-50;
        transform.position = (player1.transform.position+player2.transform.position)/2 + offset;
"

**Comment by Krasios** [comment]
Yeah, I just put an upper limit in for how back the camera moves since before it got the point where you literally couldn't see the player sprite

**Comment by Krasios** [comment]
More adjustments needed

**Pull request closed without merging**
