### PR TITLE
"Mini Map"

### PR DESCRIPTION
**Pull request by Zankey**
Created a "mini map" compas element to the UI, so that you know where the mothership is and dont get lost, also it changes from green to red the further you get away from it.

### CODE REVIEW

**Comment by connsteele** [comment]
Mothership and total light meter are overlaying eachother in the top right

**Comment by connsteele** [comment]
https://youtu.be/8n8aL0Zqmzc
Does this video exhibit the intended behavior of the UI elements?

**Comment by Zankey** [comment]
top left? weird , lemme check again

**Comment by Zankey** [comment]
video unavailable

**Comment by connsteele** [comment]
10 seconds its uploading

**Comment by connsteele** [comment]
should be visible now

**Pull request merged**
